keys:
  - &pandora_host age13mtjhs9hk7zke0jd5zmlpgsr44ffxds8hlystq6yw8h9ql20mchs495h5f

creation_rules:
  - path_regex: secrets/hosts/[^/]+\.yaml$
    key_groups:
      - age:
        - *pandora_host
  - path_regex: secrets/services/[^/]+\.yaml$
    key_groups:
      - age:
        - *pandora_host
