keys:
  - &venti_host age1th4lefmxp33f4vvewghpqmdfj7j6s5dcpzjfx3uspgxz0adt8yxq4gp8en
  - &xiao_host age1lurrquuc3rd0r3h3lq8pwqzw5fyqx2hjhhgtpnv44plhyxtph98slqg90c
  - &kazuha_user age18kfh3u8dx4qcye2xp09wgpj6xf8ycclfmzth98vkj2vw4z38j4lq07shc9

creation_rules:
  - path_regex: secrets/non\.yaml$
    key_groups:
      - age:
        - *venti_host
        - *xiao_host
        - *kazuha_user

  - path_regex: secrets/services/[^/]+$
    key_groups:
      - age:
        - *venti_host
        - *kazuha_user

  - path_regex: secrets/hosts/venti\.yaml$
    key_groups:
      - age:
        - *venti_host
        - *kazuha_user

  - path_regex: secrets/hosts/xiao\.yaml$
    key_groups:
      - age:
        - *xiao_host
        - *kazuha_user

  - path_regex: secrets/shared/xiao-venti.yaml
    key_groups:
      - age:
          - *venti_host
          - *xiao_host
          - *kazuha_user

  - path_regex: secrets/shared/wifi-pwds.yaml
    key_groups:
      - age:
          - *venti_host
          - *kazuha_user
